### ISSUE TITLE
Linker under "Administrasjon av API-integrasjoner i SSB" i "Maskinporten Guardian" leder sannsynligvis til feil område

### ISSUE THREAD

**Issue by SteffNate** [statisticsnorway/dapla-manual#116]
På slutten av avsnittet "Administrasjon av API-integrasjoner i SSB", er det en hyperlink som leder til : (https://manual.dapla.ssb.no/statistikkere/(https://docs.digdir.no/docs/Maskinporten/maskinporten_sjolvbetjening_web.html)). Denne gir page not found. regner med den skal lede hit "https://docs.digdir.no/docs/Maskinporten/maskinporten_sjolvbetjening_web.html". 

Det samme gjelder i infoboksen under. linken under registrere etter "Alle med en SSB-epostadresse kan [registerere]" leder til (https://manual.dapla.ssb.no/statistikkere/(https://user.difi.no/auth/realms/difi/login-actions/registration?client_id=samarbeid-lukket&tab_id=9q0RtrwC2Vo))". 

Er det noe feil med parentesene?

**Comment by kschulst** [comment]
Du har helt rett. Har oppdatert lenkene nå. Takk for heads up 👍
