### ISSUE TITLE
Link til contribution.html virker ikke

### ISSUE THREAD

**Issue by bryeng** [statisticsnorway/dapla-manual#125]
På https://manual.dapla.ssb.no/:
Alle ansatte i SSB kan bidra til denne manualen ved å følge [instruksjonene her](https://manual.dapla.ssb.no/contribution.html)
--> 404

**Comment by skars82** [comment]
Takk for tips, @bryeng . Er fikset nå:
https://github.com/statisticsnorway/dapla-manual/pull/132
