### ISSUE TITLE
datostempel på artikler

### ISSUE THREAD

**Issue by akcssb** [statisticsnorway/dapla-manual#143]
Jeg ønsker at hvert kapittel i manualen skal datostemples. Da kan lesere fange opp om informasjonen de leser potensielt sett er utdatert.

**Comment by skars82** [comment]
Enig i at det kan være kjekt, men det må da skje programmatisk. Ellers kan selve datoen bli utdatert. Vi kan teste ut `date-modified: last-modified` i yml-headeren i hver qmd-fil. Da får den "Endret: 5. november 2024" rett under page-title. Men siden vi bruker GH Actions så kan det hende at den oppdaterer hver gang vi bygger siden...🤔

https://quarto.org/docs/reference/dates.html

**Comment by skars82** [comment]
Testet det ut her; https://manual.dapla.ssb.no/statistikkere/hva-er-dapla-team.html

**Comment by akcssb** [comment]
> Enig i at det kan være kjekt, men det må da skje programmatisk. Ellers kan selve datoen bli utdatert. Vi kan teste ut `date-modified: last-modified` i yml-headeren i hver qmd-fil. Da får den "Endret: 5. november 2024" rett under page-title. Men siden vi bruker GH Actions så kan det hende at den oppdaterer hver gang vi bygger siden...🤔
> 
> https://quarto.org/docs/reference/dates.html

Last-modified tar for hele siden, så den vil alltid vise samme dato. Jeg lager et opplegg for å hente dato fra git commits for hver enkelt fil.
