### ISSUE TITLE
"ssb-project create <reponavn> --github" på daplalab lar en lage repo med feil brukernavn

### ISSUE THREAD

**Issue by lbissb** [statisticsnorway/dapla-manual#179]
Hvis ens github-brukernavn ikke er det som det står under Min konto -> Git (som ofte vil være tilfellet siden default er ssb-"kortnavn", noe langt fra alle har satt brukernavnet sitt til), kan man fortsatt opprette et github-repo, men da vil det være en ikke-eksisterende github-bruker som oppretter det (eller kanskje til og med noen andres profil, hvis det står en bruker der som eksisterer?).

Eksempel: jeg skrev kommando "ssb-project create lbi-play --github" etter å ha startet opp en tjeneste som ubevisst for meg inneholdt brukernavnet "ssb-lbi" under Git.

Resultatet ble et repo som er blitt opprettet av en ikke-eksisterende github-bruker:
https://github.com/statisticsnorway/lbi-play

**Comment by akcssb** [comment]
Dette hører mer hjemme i repoet ssb-project-cli. Kopierte teksten og la det inn som en issue: https://github.com/statisticsnorway/ssb-project-cli/issues/472
