### ISSUE TITLE
Forslag til kode for å lese inn .sas7bdat filer med R

### ISSUE THREAD

**Issue by sbjorkholt** [statisticsnorway/dapla-manual#67]
Hei! Jeg ser at på denne siden https://manual.dapla.ssb.no/statistikkere/jobbe-med-data.html er det listet mange flotte koder for å lese inn data. Selv har jeg opplevd at veldig mange datafiler er i SAS-format, og tenker derfor det kan være en ide å oppdatere feltet om å lese inn .sas7bdat-filer med R. Løsningen jeg foreslår her bruker reticulate, så er vel helst en midlertidig løsning, men med SAS-filer som er såpass utbredt er midlertidige løsninger bedre enn ingen løsninger tror jeg :)

Her er koden:

```
library(reticulate)
dp <- import("dapla")
sti  <- gs://ssb-dapla-felles-data-delt-prod/felles/veiledning/sas/statbank_ledstill.sas7bdat"
dp$read_pandas(sti, file_format="sas7bdat", encoding="latin1")
```

Takk for flott arbeid med en veldig god manual.

Hilsen Solveig

**Comment by skars82** [comment]
Bra forslag, @sbjorkholt! La inn en PR med koden din her: https://github.com/statisticsnorway/dapla-manual/pull/73

Den fremgangsmåten kan jo brukes alle steder hvor det ikke finnes noe alternativ i fellesr
