### ISSUE TITLE
Bucket ref til felles-delt er feil?

### ISSUE THREAD

**Issue by josteist** [statisticsnorway/dapla-manual#78]
De fleste steder (med R eksempler) har feil ref til eksempelbøtta i "Jobbe med data". Det står:
ssb-dapla-felles-data-delt-prod

Men riktig er:
ssb-prod-dapla-felles-data-delt

Ellers så fungerer ikke list.files(), men gcs.list.files() vil fungere.

**Comment by skars82** [comment]
Takk for påminnelsen. Vi er i ferd med å migrere dapla-felles teamet, men det ser ikke til at tilgangene er helt på plass. `ssb-dapla-felles-data-delt-prod` er den nye strukturen. Skal få noen til å fikse tilgangsproblemet kjapt

**Comment by skars82** [comment]
Da har vi endret filstier til produkt-bøtta til nye Dapla Felles.
