### ISSUE TITLE
Broken url

### ISSUE THREAD

**Issue by mfmssb** [statisticsnorway/dapla-manual#80]
“[uforandelighet av data](https://statistics-%20norway.atlassian.net/wiki/spaces/ARK/pages/2839707937/Prinsipp+1+Uforanderlighet+av+data)”

Gir feilmelding "Dette nettstedet er ikke tilgjengelig"

**Comment by skars82** [comment]
Lenke er nå endret. https://github.com/statisticsnorway/dapla-manual/pull/81
